import assert from 'node:assert/strict';
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { PassThrough } from 'node:stream';
import { afterEach, test } from 'vitest';
import { run } from '../cli.js';
import {
  buildCursorUserRulesExport,
  renderCursorUserRulesText,
} from '../export-cursor-user-rules.js';
import { createProgram, type HarnessmithCommand } from '../program.js';
import { packageVersion } from '../install-template.js';
import type { CliOptions } from '../types.js';

const tempRoots: string[] = [];

afterEach(() => {
  while (tempRoots.length > 0) {
    const root = tempRoots.pop();
    if (root) rmSync(root, { recursive: true, force: true });
  }
});

function tempRoot(): string {
  const root = mkdtempSync(join(tmpdir(), 'harnessmith-export-'));
  tempRoots.push(root);
  return root;
}

function directorySnapshot(root: string): string[] {
  const entries: string[] = [];
  const walk = (dir: string, relative = ''): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const child = relative ? join(relative, entry.name) : entry.name;
      entries.push(entry.isDirectory() ? `${child}/` : child);
      if (entry.isDirectory()) walk(join(dir, entry.name), child);
    }
  };
  walk(root);
  return entries.sort();
}

test('renderCursorUserRulesText matches the paste-ready snapshot with version footer', () => {
  const text = renderCursorUserRulesText('9.9.9-test');
  assert.equal(
    text,
    [
      '- 项目根存在 AGENTS.md 或 .cursor/rules/ 时，先读并遵循；项目规则优先于本全局规则。',
      '- 项目存在 .cursor/agent-harness/ 时，可用 node .cursor/agent-harness/bin/harness.mjs 使用 harness 的 search / memory / task 能力。',
      '- ~/.agent-harness/ 存在时视为个人通用工作方式；与项目规则冲突时以项目规则为准。',
      '- 以上文件缺失时不要臆造规则：缺失仅表示该宿主/项目未安装 harnessmith。',
      '',
      '<!-- generated by harnessmith 9.9.9-test via `export cursor-user-rules`; re-run after upgrades -->',
      '',
    ].join('\n'),
  );
});

test('buildCursorUserRulesExport shapes the --json payload', () => {
  assert.deepEqual(buildCursorUserRulesExport('0.9.0'), {
    target: 'cursor-user-rules',
    text: renderCursorUserRulesText('0.9.0'),
    version: '0.9.0',
    out: null,
  });
  assert.equal(buildCursorUserRulesExport('0.9.0', '/tmp/rules.txt').out, '/tmp/rules.txt');
});

test('default export prints text to stdout and writes zero files', async () => {
  const root = tempRoot();
  mkdirSync(join(root, 'probe'));
  writeFileSync(join(root, 'probe', 'keep.txt'), 'keep');
  const before = directorySnapshot(root);
  const logs: string[] = [];
  const code = await run(['export', 'cursor-user-rules'], {
    io: { log: (value) => logs.push(String(value)) },
    input: new PassThrough(),
    output: new PassThrough(),
  });
  assert.equal(code, 0);
  assert.equal(logs.join('\n'), renderCursorUserRulesText(packageVersion));
  assert.deepEqual(directorySnapshot(root), before);
});

test('export --json prints the complete machine-readable payload', async () => {
  const logs: string[] = [];
  const code = await run(['export', 'cursor-user-rules', '--json'], {
    io: { log: (value) => logs.push(String(value)) },
    input: new PassThrough(),
    output: new PassThrough(),
  });
  assert.equal(code, 0);
  assert.deepEqual(JSON.parse(logs[0]), {
    target: 'cursor-user-rules',
    text: renderCursorUserRulesText(packageVersion),
    version: packageVersion,
    out: null,
  });
});

test('export --out creates a new file and refuses existing targets without --force', async () => {
  const root = tempRoot();
  const out = join(root, 'cursor-user-rules.txt');
  const logs: string[] = [];
  const created = await run(['export', 'cursor-user-rules', '--out', out], {
    io: { log: (value) => logs.push(String(value)) },
    input: new PassThrough(),
    output: new PassThrough(),
  });
  assert.equal(created, 0);
  assert.equal(readFileSync(out, 'utf8'), renderCursorUserRulesText(packageVersion));
  assert.equal(logs.length, 0);

  let refused: unknown;
  try {
    await run(['export', 'cursor-user-rules', '--out', out], {
      io: { log: () => undefined },
      input: new PassThrough(),
      output: new PassThrough(),
    });
  } catch (error) {
    refused = error;
  }
  assert.ok(refused instanceof Error);
  assert.match(String(refused), /require --force|use --force/i);
  assert.equal(existsSync(out), true);
  assert.equal(readFileSync(out, 'utf8'), renderCursorUserRulesText(packageVersion));

  writeFileSync(out, 'stale\n');
  const forcedLogs: string[] = [];
  const forced = await run(['export', 'cursor-user-rules', '--out', out, '--force', '--json'], {
    io: { log: (value) => forcedLogs.push(String(value)) },
    input: new PassThrough(),
    output: new PassThrough(),
  });
  assert.equal(forced, 0);
  assert.equal(readFileSync(out, 'utf8'), renderCursorUserRulesText(packageVersion));
  assert.deepEqual(JSON.parse(forcedLogs[0]), {
    target: 'cursor-user-rules',
    text: renderCursorUserRulesText(packageVersion),
    version: packageVersion,
    out,
  });
});

test('Commander wires export cursor-user-rules with out and force flags', async () => {
  let result: (CliOptions & { command: HarnessmithCommand }) | undefined;
  const program = createProgram(async (command, options) => {
    result = { command, ...options };
  });
  await program.parseAsync(
    ['export', 'cursor-user-rules', '--out', '/tmp/rules.txt', '--force', '--json'],
    { from: 'user' },
  );
  assert.ok(result);
  assert.equal(result.command, 'export-cursor-user-rules');
  assert.equal(result.out, '/tmp/rules.txt');
  assert.equal(result.force, true);
  assert.equal(result.json, true);
});
