import { existsSync } from 'node:fs';
import { atomicWrite } from './files.js';
import { packageVersion } from './install-template.js';
import type { Io } from './types.js';
import { HarnessmithError } from './types.js';

export const CURSOR_USER_RULES_TARGET = 'cursor-user-rules' as const;

export interface CursorUserRulesExport {
  target: typeof CURSOR_USER_RULES_TARGET;
  text: string;
  version: string;
  out: string | null;
}

export function renderCursorUserRulesText(version: string): string {
  return [
    '- 项目根存在 AGENTS.md 或 .cursor/rules/ 时，先读并遵循；项目规则优先于本全局规则。',
    '- 项目存在 .cursor/agent-harness/ 时，可用 node .cursor/agent-harness/bin/harness.mjs 使用 harness 的 search / memory / task 能力。',
    '- ~/.agent-harness/ 存在时视为个人通用工作方式；与项目规则冲突时以项目规则为准。',
    '- 以上文件缺失时不要臆造规则：缺失仅表示该宿主/项目未安装 harnessmith。',
    '',
    `<!-- generated by harnessmith ${version} via \`export cursor-user-rules\`; re-run after upgrades -->`,
    '',
  ].join('\n');
}

export function buildCursorUserRulesExport(
  version: string,
  out: string | null = null,
): CursorUserRulesExport {
  return {
    target: CURSOR_USER_RULES_TARGET,
    text: renderCursorUserRulesText(version),
    version,
    out,
  };
}

export function writeCursorUserRulesOut(path: string, text: string, force = false): void {
  if (existsSync(path) && !force) {
    throw new HarnessmithError(
      'SAFETY_CONFLICT',
      `Existing unmanaged or modified files require --force:\n  ${path}`,
      3,
    );
  }
  atomicWrite(path, text);
}

export function executeExportCursorUserRules(
  options: { out?: string; force?: boolean; json?: boolean },
  context: { io: Io },
  version = packageVersion,
): number {
  const out = options.out ?? null;
  const payload = buildCursorUserRulesExport(version, out);
  if (out) writeCursorUserRulesOut(out, payload.text, Boolean(options.force));
  if (options.json) context.io.log(JSON.stringify(payload));
  else if (!out) context.io.log(payload.text);
  return 0;
}
